CREATE TABLE weight_records (
    id UUID PRIMARY KEY,
    pet_id UUID NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_weight_pet FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);
